/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  coummunityArticlesSidebar: [{ type: 'autogenerated', dirName: 'community_articles' }],

  // But you can create a sidebar manually
  // coummunityArticlesSidebar: [
  //   'community_articles/coummunity_articles',
  //   {
  //     type: 'category',
  //     label: 'Community Articles',
  //     items: ['community_articles/template', 'community_articles/coummunity_articles'],
  //   },
  // ],

};

module.exports = sidebars;
